### ISSUE TITLE
UnMakeMove

### ISSUE THREAD

**Issue by athaa** [jordanbray/chess#28]
Hello,

First thanks for the fantastic job ! You make me able to almost (work still in progress) create an UCI engine quite rapidly.

is there a clean way to unmake a move ? The only way I could see is to truncate the game.actions() list to remove last MakeMove(ChessMove)  but I think it should be a simpler way ?

The need is to implement the ponder uci feature. when entering in ponder search mode, the last move played is the ponder move (note: when playing the move on the game, we don't know yet it will be a ponder move) . As we don't have to only check for the pondered move (UIC protocol allow that), we need to unmake the move before searching. 

Any advice how to implement this in other way is welcome.

**Comment by jordanbray** [comment]
There is not an easy way to unmake a move, because the library is
copy-on-make. The data structure for the board is optimized for size, so
copying the structure before you make a move is actually faster than
unmaking a move.

I did some testing initially to confirm this. I also figured copy-on-make
was more idiomatic rust.

Thanks,
Jordan

**Comment by athaa** [comment]
Good points ! I will go with the copy then.

Thanks for rapid and precise reply,
Gabriel
